services:
  - type: web
    name: bookstore-app  # can be any name you like
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore_db
          property: connectionString

databases:
  - name: bookstore-db
    databaseName: bookstore
    user: bookstore_user

