# Generated by Django 5.2.4 on 2025-07-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_wishlist'),
    ]

    operations = [
    ]
